import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'home', loadComponent: () => import('./pages/home/home.component').then(m => m.HomeComponent) },
  { path: 'login', loadComponent: () => import('./pages/login/login.component').then(m => m.LoginComponent) },
  { path: 'register', loadComponent: () => import('./pages/register/register.component').then(m => m.RegisterComponent) },
  { path: 'forgot-password', loadComponent: () => import('./pages/forgot-password/forgot-password.component').then(m => m.ForgotPasswordComponent) },  { path: 'modules', loadComponent: () => import('./pages/modules/modules.component').then(m => m.ModulesComponent) },
  { path: 'modules/:id', loadComponent: () => import('./pages/module/module.component').then(m => m.ModuleComponent) },
  { path: 'admin', redirectTo: 'admin/users', pathMatch: 'full' },
  { path: 'admin/modules', loadComponent: () => import('./pages/admin-module-management/admin-module-management.component').then(m => m.AdminModuleManagementComponent) },
  { path: 'admin/registrations', loadComponent: () => import('./pages/admin-pending-registrations/admin-pending-registrations.component').then(m => m.AdminPendingRegistrationsComponent) },
  { path: 'admin/users', loadComponent: () => import('./pages/admin-user-management/admin-user-management.component').then(m => m.AdminUserManagementComponent) },
  { path: 'chat', loadComponent: () => import('./pages/chat/chat.component').then(m => m.ChatComponent) },
  { path: 'enquiries', loadComponent: () => import('./pages/enquiries/enquiries.component').then(m => m.EnquiriesComponent) },
  { path: 'enquiries/history', loadComponent: () => import('./pages/enquiries-history/enquiries-history.component').then(m => m.EnquiriesHistoryComponent) },
  { path: 'admin/enquiries', loadComponent: () => import('./pages/enquiries-management/enquiries-management.component').then(m => m.EnquiriesManagementComponent) },
  { path: 'profile', loadComponent: () => import('./pages/profile-detail/profile-detail.component').then(m => m.ProfileDetailComponent) },
  { path: 'profile/change-password', loadComponent: () => import('./pages/profile-change-password/profile-change-password.component').then(m => m.ProfileChangePasswordComponent) },
  { path: 'profile/topics', loadComponent: () => import('./pages/profile-topic-subscriptions/profile-topic-subscriptions.component').then(m => m.ProfileTopicSubscriptionsComponent) },
  { path: 'profile/tutors', loadComponent: () => import('./pages/profile-tutor-subscriptions/profile-tutor-subscriptions.component').then(m => m.ProfileTutorSubscriptionsComponent) },
  { path: 'quiz/:id/attempt', loadComponent: () => import('./pages/quiz-attempt/quiz-attempt.component').then(m => m.QuizAttemptComponent) },
  { path: 'quiz/:id/review', loadComponent: () => import('./pages/quiz-attempt-review/quiz-attempt-review.component').then(m => m.QuizAttemptReviewComponent) },
  { path: 'quiz/history', loadComponent: () => import('./pages/quiz-history/quiz-history.component').then(m => m.QuizHistoryComponent) },
  { path: 'quiz/:id/management', loadComponent: () => import('./pages/quiz-management/quiz-management.component').then(m => m.QuizManagementComponent) },
  { path: 'quizzes', loadComponent: () => import('./pages/quizzes/quizzes.component').then(m => m.QuizzesComponent) },
  { path: 'terms-and-conditions', loadComponent: () => import('./pages/terms-and-conditions/terms-and-conditions.component').then(m => m.TermsAndConditionsComponent) },
  { path: 'topic/:id', loadComponent: () => import('./pages/topic/topic.component').then(m => m.TopicComponent) },
  { path: 'topic/:id/discussions', loadComponent: () => import('./pages/topic-discussions/topic-discussions.component').then(m => m.TopicDiscussionsComponent) },
  { path: 'topic/:id/learning-material', loadComponent: () => import('./pages/topic-learning-material/topic-learning-material.component').then(m => m.TopicLearningMaterialComponent) },
  { path: 'topic/:id/quizzes', loadComponent: () => import('./pages/topic-quizzes/topic-quizzes.component').then(m => m.TopicQuizzesComponent) },
];
