IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QuizAttemptQuestionAnswer')
BEGIN
	CREATE TABLE QuizAttemptQuestionAnswer (
		Id UNIQUEIDENTIFIER PRIMARY KEY,
		QuizAttemptId UNIQUEIDENTIFIER NOT NULL,
		QuestionId UNIQUEIDENTIFIER NOT NULL,
		QuestionOptionId UNIQUEIDENTIFIER NOT NULL,
		IsCorrect BIT NOT NULL,
		FOREIGN KEY (QuizAttemptId) REFERENCES QuizAttempt(Id),
		FOREIGN KEY (QuestionId) REFERENCES Question(Id),
		FOREIGN KEY (QuestionOptionId) REFERENCES QuestionOption(Id)
	);
END;