IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Statuses')
BEGIN
    CREATE TABLE [dbo].[Statuses] (
        Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        Description NVARCHAR(255) NOT NULL
    )
END