IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TutorSubscription')
BEGIN
    CREATE TABLE TutorSubscription (
        Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        UserId UNIQUEIDENTIFIER NOT NULL,
        TutorId UNIQUEIDENTIFIER NOT NULL,
        DateSubscribed DATETIME DEFAULT GETDATE(),
        FOREIGN KEY (UserId) REFERENCES [User](Id),
        FOREIGN KEY (TutorId) REFERENCES [User](Id)
    )
END