IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'User')
BEGIN
    CREATE TABLE [User] (
        Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        Name NVARCHAR(255) NOT NULL,
        MiddleName VARCHAR(255) NULL,
        Surname NVARCHAR(255) NOT NULL,
        Email NVARCHAR(255) NOT NULL UNIQUE,
        Password NVARCHAR(255) NOT NULL,
        ContactNumber NVARCHAR(20),
        Role INT NOT NULL,
		AccountStatus UNIQUEIDENTIFIER DEFAULT('7DCF4027-85AA-4C08-92FF-F3A669DFF157'),
        CONSTRAINT FK_User_AccountStatus FOREIGN KEY (AccountStatus) REFERENCES [Statuses](Id),
    )
END
ELSE
BEGIN
	IF NOT EXISTS (SELECT * FROM syscolumns WHERE ID=OBJECT_ID('dbo.User') AND NAME='AccountStatus')
	BEGIN
		ALTER TABLE [dbo].[User] ADD [AccountStatus] UNIQUEIDENTIFIER DEFAULT('7DCF4027-85AA-4C08-92FF-F3A669DFF157')
		REFERENCES [dbo].[Statuses](Id)
	END
    IF NOT EXISTS (SELECT * FROM syscolumns WHERE ID=OBJECT_ID('dbo.User') AND NAME='MiddleName')
	BEGIN
		ALTER TABLE [dbo].[User] ADD [MiddleName] VARCHAR(255) NULL DEFAULT('')
	END
END