// Mock quiz data

import { Quiz } from './interfaces';

export const mockQuizzes: Quiz[] = [
  {
    id: 1,
    topicId: 1,
    name: 'Angular Fundamentals Quiz',
    description: 'Test your understanding of Angular basics, components, and data binding concepts.',
    duration: 30,
    totalQuestions: 15,
    passingScore: 70,
    difficulty: 'Easy',
    status: 'Active',
    createdDate: new Date('2024-01-15'),
    dueDate: new Date('2024-02-15'),
    attempts: 0,
    maxAttempts: 3
  },
  {
    id: 2,
    topicId: 1,
    name: 'Component Lifecycle Assessment',
    description: 'Advanced quiz covering Angular component lifecycle hooks and their practical applications.',
    duration: 45,
    totalQuestions: 20,
    passingScore: 75,
    difficulty: 'Medium',
    status: 'Active',
    createdDate: new Date('2024-01-20'),
    dueDate: new Date('2024-03-01'),
    attempts: 1,
    maxAttempts: 2
  },
  {
    id: 3,
    topicId: 1,
    name: 'Services and Dependency Injection',
    description: 'Comprehensive quiz on Angular services, dependency injection, and best practices.',
    duration: 60,
    totalQuestions: 25,
    passingScore: 80,
    difficulty: 'Hard',
    status: 'Active',
    createdDate: new Date('2024-01-25'),
    dueDate: new Date('2024-03-15'),
    attempts: 0,
    maxAttempts: 1
  },
  {
    id: 4,
    topicId: 1,
    name: 'Angular Routing Quiz',
    description: 'Test your knowledge of Angular Router, guards, and navigation concepts.',
    duration: 35,
    totalQuestions: 18,
    passingScore: 70,
    difficulty: 'Medium',
    status: 'Draft',
    createdDate: new Date('2024-01-30'),
    attempts: 0,
    maxAttempts: 3
  },
  {
    id: 5,
    topicId: 1,
    name: 'Forms and Validation',
    description: 'Quiz covering reactive forms, template-driven forms, and validation techniques in Angular.',
    duration: 40,
    totalQuestions: 22,
    passingScore: 75,
    difficulty: 'Medium',
    status: 'Active',
    createdDate: new Date('2024-02-01'),
    dueDate: new Date('2024-03-20'),
    attempts: 2,
    maxAttempts: 3
  },
  {
    id: 6,
    topicId: 1,
    name: 'Angular Directives',
    description: 'Assessment on built-in and custom directives, structural and attribute directives.',
    duration: 25,
    totalQuestions: 12,
    passingScore: 70,
    difficulty: 'Easy',
    status: 'Active',
    createdDate: new Date('2024-02-05'),
    dueDate: new Date('2024-03-25'),
    attempts: 0,
    maxAttempts: 2
  },
  {
    id: 7,
    topicId: 1,
    name: 'HTTP Client and Observables',
    description: 'Advanced quiz on Angular HTTP client, RxJS observables, and asynchronous programming.',
    duration: 50,
    totalQuestions: 30,
    passingScore: 80,
    difficulty: 'Hard',
    status: 'Archived',
    createdDate: new Date('2024-01-10'),
    attempts: 3,
    maxAttempts: 3
  },
  {
    id: 8,
    topicId: 1,
    name: 'Angular Testing Basics',
    description: 'Introduction to unit testing in Angular with Jasmine and Karma.',
    duration: 45,
    totalQuestions: 20,
    passingScore: 75,
    difficulty: 'Medium',
    status: 'Active',
    createdDate: new Date('2024-02-10'),
    dueDate: new Date('2024-04-01'),
    attempts: 0,
    maxAttempts: 2  }
];
